blog/urls.py
from django.urls import path
from .views import BlogView, DetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogView.as_view(), name='bloglist'),
    path('details/<int:pk>', DetailView.as_view(), name='detailview'),
    ]

bloggest/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio import views
from portfolio.views import UpdateBlog,DisplayHome, AuthorPageView,CreateBlog,DeleteBlog,DisplayAuthors,PersonalProfile, CreateProfile,UpdateProfile
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('', DisplayHome.as_view(), name='home'),
    path('authors/', DisplayAuthors.as_view(), name='authors'),
    path('personalprofile/', login_required(PersonalProfile.as_view()), name='personalprofile'),
    path('authorpage/', login_required(cache_page(60*60)(AuthorPageView.as_view())), name='authorpage'),
    path('create/', login_required(CreateBlog.as_view()), name='create'),
    path('createprofile/', login_required(CreateProfile.as_view()), name='createprofile'),
    path('update/<int:pk>', login_required(UpdateBlog.as_view()), name='updateblog'),
    path('updateprofile/<int:pk>', login_required(UpdateProfile.as_view()), name='updateprofile'),
    path('delete/<int:pk>', login_required(DeleteBlog.as_view()), name='deleteblog'),
    path('blog/', include('blog.urls', namespace='blog')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Author(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    Name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='portfolio/images/', null=True, blank=True)
    Bio = models.TextField(max_length=150, null=True)
    Location = models.CharField(max_length=150)
    Work = models.TextField(max_length=150)

    def __str__(self):
        return self.Name

portfolio/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from blog.models import Blog
from portfolio.models import Author


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    class Meta:
        model = User
        fields = ('username', 'email')


class LogInForm(AuthenticationForm):
    email = forms.EmailField(label="Email")
    class Meta:
        model = User
        fields = ('username', 'email')


class CreateBlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'tag', 'image','body')

class AuthorProfileForm(ModelForm):
    class Meta:
        model = Author
        fields = ('Name', 'image', 'Bio','Location', 'Work')

portfolio/views.py
from django.contrib.auth import login, authenticate, logout
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from blog.models import Blog
from .forms import SignUpForm, LogInForm, CreateBlogForm, AuthorProfileForm
from django.shortcuts import render, redirect
from django.views.generic import View
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from django.utils import timezone
from portfolio.models import Author


class DisplayHome(TemplateView):
    template_name = 'portfolio/home.html'


class AuthorPageView(ListView):
    template_name = 'portfolio/author_page.html'
    pk_url_kwarg = 'pk'
    context_object_name = 'blogs'
    paginate_by = 2

    def get_queryset(self):
        return Blog.objects.filter(author=self.request.user).order_by('-date_created')


class DisplayAuthors(ListView):
    template_name = 'portfolio/authors_list.html'
    context_object_name = 'authors'

    def get_queryset(self):
        return Author.objects.all().order_by('Name')


class PersonalProfile(ListView):
    template_name = 'portfolio/author_profile.html'
    context_object_name = 'authors'

    def get_queryset(self):
        return Author.objects.filter(username=self.request.user)


class CreateProfile(CreateView):
    form_class = AuthorProfileForm
    template_name = 'portfolio/author_create.html'
    success_url = reverse_lazy('personalprofile')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.username = self.request.user
        self.object.save()
        return super().form_valid(form)


class UpdateProfile(UpdateView):
    form_class = AuthorProfileForm
    pk_url_kwarg = 'pk'
    model = Author
    template_name = 'portfolio/author_update.html'
    success_url = '/personalprofile/'


class CreateBlog(CreateView):
    form_class = CreateBlogForm
    template_name = 'portfolio/create.html'
    success_url = reverse_lazy('authorpage')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class UpdateBlog(UpdateView):
    form_class = CreateBlogForm
    pk_url_kwarg = 'pk'
    model = Blog
    template_name = 'portfolio/update.html'
    success_url = '/authorpage/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.date_updated = timezone.now()
        self.object.save()
        return super().form_valid(form)


class DeleteBlog(DeleteView):
    pk_url_kwarg = 'pk'
    model = Blog
    success_url = '/authorpage/'


def signupuser(request):
    context = {'form': SignUpForm()}
    if request.method == 'GET':
        return render(request, 'portfolio/signup.html', context)
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'],
                                                email=request.POST['email'])
                user.save()
                ##### uncomment this to send mail#######
                # subject = 'Welcome To Bloggest Family!'
                # message = 'Thank you for joining Bloggest.! you can immedietely log in and start writing blogs. Happy Writing!'
                # from_email = settings.EMAIL_HOST_USER
                # to_list = [request.POST['email'],]
                # send_mail(subject=subject, message=message, from_email=from_email, recipient_list=to_list, fail_silently=True)
                login(request, user)
                return redirect('blog:bloglist')
            except IntegrityError:
                context = {'form': SignUpForm(), 'error': ' The username already exists. Please try again!'}
                return render(request, 'portfolio/signup.html', context)
        else:
            context = {'form': SignUpForm(), 'error': ' The passwords do not match. Try again!'}
            return render(request, 'portfolio/signup.html', context)


def loginuser(request):
    context = {'form': LogInForm()}
    if request.method == 'GET':
        return render(request, 'portfolio/login.html', context)
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            context = {'form': LogInForm(), 'error': 'The username or password did not match'}
            return render(request, 'portfolio/login.html', context)
        else:
            login(request, user)
            return redirect('authorpage')


def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

portfolio/templates/portfolio/author_create.html
{% extends 'portfolio/base.html' %}
{% block content%}
<div class="create-form">
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-info" type="submit">Save</button>
    </form>
    </div>
{% endblock %}

portfolio/templates/portfolio/author_page.html
{% extends 'portfolio/base.html' %}
{% block content%}

<h2 class="blog_title">Here are your blogs!</h2><br>
<div class="blog-body">
<ul>
{% for blog in blogs%}
 <li>
        <a href="{% url 'blog:detailview' blog.id %}"><h2>{{blog.title}}</h2></a>
       {% if blog.date_updated %}
         <h5>Updated by {{blog.author| capfirst}} on: {{blog.date_updated | date:'M j Y H:i' }}</h5>
        {% else %}
        <h5>Posted by {{blog.author| capfirst}} on: {{blog.date_created | date:'M j Y H:i' }}</h5>
        {% endif %}
        <h5>Tag : {{blog.tag}}</h5>
        <p>{{blog.body | truncatechars:120}}</p>
    <div class="form-buttons">
     <form action="{% url 'updateblog' blog.id %}" method="GET">
         {% csrf_token %}
         <button class="btn btn-sm btn-warning" type="submit">Update</button>
     </form>

     <form action="{% url 'deleteblog' blog.id %}" method="POST">
         {% csrf_token %}
         <button class="btn btn-sm btn-danger" type="submit">Delete</button>
     </form>
    </div>
    </li>
    <br>
    <hr>
 {% endfor %}
</ul>
</div>
<br>
{% if is_paginated %}
  <nav aria-label="Page navigation conatiner"></nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

    {% endif %}
  </ul>
  </nav>
</div>
{% endif %}
{% endblock %}

portfolio/templates/portfolio/author_profile.html
{% extends 'portfolio/base.html' %}
{% block content%}
{% load static %}

<div class="blog-body">
    {% if not authors %}
    <a href="{% url 'createprofile' %}">
            <button class="btn btn btn-info">Create Profile</button>
        </a>
    {% endif %}
    <ul>
        {% for author in authors %}
        <li>
            <div class="author-profile">
                {% if author.image %}
                <div class="bio-img">
                    <img height="100" src="{{author.image.url}}" width="100"/>
                </div>
                {%endif%}
                <div class="bio">
                    <b>Username</b> : {{author.username}}<br>
                    <b>Name</b> : {{author.Name}}<br>
                    <b>Location</b> : {{author.Location}}<br>
                    <b>Bio</b> : {{author.Bio}}<br>
                    <b>Work</b> : {{author.Work}}<br>
                </div>
                <div class="form-buttons">
                    <form action="{%url 'updateprofile' author.id %}" method="GET">
                        <button class="btn btn-sm btn-warning" type="submit">Update Profile</button>
                    </form>
                </div>
            </div>
        </li>
        <hr>
        {% endfor %}
    </ul>
</div>

{% endblock %}

portfolio/templates/portfolio/author_update.html
{% extends 'portfolio/base.html' %}
{% block content%}
<div class="create-form">
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-info" type="submit">Save</button>
    </form>
    </div>
{% endblock %}

portfolio/templates/portfolio/authors_list.html
{% extends 'portfolio/base.html' %}
{% block content%}
{% load static %}

<div class="blog-body">
<ul>
    {% for author in authors%}

    <li>
        <div class="author-profile">
        <div class="bio-img">
            <img height="100" src="{{author.image.url}}" width="100"/>
        </div>
        <div class="bio">
        <b>Username</b> : {{author.username}}<br>
        <b>Name</b> : {{author.Name}}<br>
        <b>Location</b> : {{author.Location}}<br>
        <b>Bio</b> : {{author.Bio}}<br>
        <b>Work</b> : {{author.Work}}<br>
        </div>
    </li>
    <hr>
    {% endfor %}
</ul>
</div>

{% endblock %}

portfolio/templates/portfolio/base.html
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blogger | Home</title>
    <link href="{% static 'portfolio/custom.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">


</head>
<body>
<nav class="navbar">
    <div class="nav-wrapper">
        <div class="regular-nav">
            <a href="{% url 'home' %}">HOME</a>
            <a href="{% url 'blog:bloglist' %}">BLOGS</a>
            <a href="{% url 'authors' %}">AUTHORS</a>
        </div>
        <div class="auth-nav">
            {% if user.is_authenticated %}
            <h5>Hello {{user.username}}!</h5>
            <a class="btn btn-primary" href="{% url 'create' %}">Create New Blog</a>
            <a class="btn btn-primary" href="{% url 'authorpage' %}">My Blogs</a>
            <a class="btn btn-primary" href="{% url 'personalprofile' %}">My Profile</a>

            <form action="{% url 'logoutuser' %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-sm btn-danger" type="submit">Log Out</button>
            </form>
            <br>
            {% else %}
            <a class="btn btn-primary" href="{% url 'signupuser' %}">Sign Up To Be an Author</a>
            <a class="btn btn-primary" href="{% url 'loginuser' %}">Log In As Author</a>
            {% endif %}
            <br><br>
        </div>
    </div>
</nav>
<br>
<div class="container">
    {% block content %}{% endblock %}
</div>

</body>
</html>

portfolio/templates/portfolio/create.html
{% extends 'portfolio/base.html' %}
{% block content%}
<div class="create-form">
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
<!--     <div class="form-group">-->
<!--       <span class="create-label">{{ field.label_tag }}</span>  <span class="create-field"> {{ field }}</span>-->
<!--    </div>-->
    <button class="btn btn-info" type="submit">Save</button>
    </form>
    </div>
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content%}
{% load static %}

<div class="home-wrapper">
    <h1>WELCOME TO BLOGGEST!</h1>
    <br>
    <p>Welcome to our blog that is entirely dedicated to bringing you news and stories from our authors so you can
        remain up-to-date
        with all that is happening in the technical world.<br>
        if you are here as a <b>READER</b>, please fo to our blog page to find an article that might interest you. If
        you are a <b>WRITER</b>, interested to contribute to our site, sign up as author and start posting your blogs
    </p>
    <br>
    <a class="btn btn-info" href="{% url 'blog:bloglist' %}">Go to blog page</a>
</div>

{% endblock %}

portfolio/templates/portfolio/login.html
{%load static%}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blogger | Signup</title>
    <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body class="signup">

<div class="container">
    <div class="signup-container">

        <h1>Log In as Author</h1>
        <br>
        <div class="signup-wrapper">
        <h4 class="err">{{error}}</h4>
        <br>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-info" type="submit">Log In</button>
        </form>
    </div>
</div>
</div>
</body>
</html>

portfolio/templates/portfolio/signup.html
{%load static%}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blogger | Signup</title>
    <link href="{% static 'portfolio/custom.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
</head>
<body class="signup">

<div class="container">
    <div class="signup-container">

        <h1>Sign Up</h1>
        <br>
        <div class="signup-wrapper">
            <h4 class="err">{{error}}</h4>
            <br>
            <form method="POST">
                {% csrf_token %}
                <!--                {{form.as_p}}-->
                {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }} {{ field }}
                </div>
                {% endfor %}
                <button class="btn btn-info" type="submit">Signup</button>
            </form>
        </div>
    </div>
</div>
</div>
</body>
</html>

portfolio/templates/portfolio/update.html
{% extends 'portfolio/base.html' %}
{% block content%}
<div class="create-form">
<form action="{% url 'updateblog' blog.id %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-info" type="submit">Save</button>
    </form>
    </div>
{% endblock %}